# Generated by Django 6.0.5 on 2026-06-02 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('observacion', models.CharField(blank=True, max_length=256, null=True)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='aulas.aula')),
            ],
            options={
                'db_table': 'aulas_reserva_aula',
            },
        ),
        migrations.CreateModel(
            name='HorarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='aulas.materia')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='aulas.reservaaula')),
            ],
            options={
                'db_table': 'aulas_horario_materia',
            },
        ),
    ]
