# Generated by Django 6.0.5 on 2026-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_reservaaula_horariomateria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaaula',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
